Repository COVID19Tracking/website, pull requests merged in 2020-03, with the labels that each got.

#13 Initial style sketch for the State Notes page
  _src/_assets/css/_states.scss
  _src/_assets/css/all.scss
  _src/_templates/base.njk
  _src/_templates/states.njk
Labels: enhancement, question

#48 Adding in a .editorconfig
  .editorconfig
Labels: enhancement

#64 Updated colors for links & buttons (per #63); active page indicator
  _src/_assets/css/_button.scss
  _src/_assets/css/_globals.scss
  _src/_assets/css/_header.scss
  _src/_assets/css/_variables.scss
  _src/_templates/base.njk
  _src/_templates/partials/footer.njk
  _src/_templates/partials/header.njk
Labels: enhancement

#65 Navigation copy updates (per #63)
  _src/_templates/partials/header.njk
Labels: enhancement

#73 Minor style tweaks, post-state pages
  _src/_assets/css/_globals.scss
  _src/_assets/css/_states.scss
  _src/_assets/css/_usDaily.scss
  _src/_templates/partials/header.njk
  _src/_templates/states.njk
Labels: DESIGN, enhancement

#85 List tweaks! (closes #82)
  _src/_assets/css/_globals.scss
  _src/_assets/css/_layout.scss
Labels: DESIGN, enhancement

#142 [⚠WIP] Redo nav
  _src/_templates/partials/footer.njk
  _src/_templates/partials/header.njk
Labels: CONTENT/EDITORIAL, DESIGN

#188 changing press endpoint to conform to others and not hit the cache
  _src/_data/sheets.js
Labels: API

#187 [WIP ⚠] Design 2.0
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/common/alert.js
  src/components/common/button.js
  src/components/common/container.js
  src/components/common/detail-text.js
  src/components/common/hero.js
  src/components/common/press.js
  src/components/common/summary-table.js
  src/components/layout/development-warning.js
  src/components/layout/header.js
  src/components/layout/index.js
  src/content/pages/help.md
  src/content/pages/index.mdx
  src/data/navigation/header.yml
  src/images/hero-bg.svg
  src/images/project-logo.svg
  src/pages/data/historical.js
  src/pages/data/index.js
  src/scss/components/common/container.scss
  src/scss/components/common/detail-text.scss
  src/scss/components/common/hero.scss
  src/scss/components/development-warning.scss
  src/scss/components/header.scss
  src/scss/components/hero.scss
  src/scss/global.scss
  src/scss/normalize.css
  src/scss/pages/data.scss
  src/stories/00-Layout.stories.js
  src/stories/06-Detail-text.stories.js
  src/stories/09-Tables.stories.js
  src/stories/12-Press-links.stories.js
  src/stories/13-Development-warning.stories.js
  src/stories/15-Container.stories.js
  src/templates/content.js
  src/templates/state.js
  src/utilities/typography.js
Labels: DESIGN, DEV

#224 Add Infobox component
  src/components/common/build-time.js
  src/components/common/infobox.js
  src/images/infobox-icons/alert.svg
  src/images/infobox-icons/question.svg
  src/images/infobox-icons/sync.svg
  src/pages/data/historical.js
  src/pages/data/index.js
  src/scss/components/common/infobox.scss
  src/stories/13-Infobox.stories.js
  src/templates/state.js
Labels: DESIGN

#258 Use same x axis for all small multiples charts
  _src/_assets/js/d3-area-chart.js
  _src/_assets/js/dashboard-charts.js
Labels: Visualization 📈

#263 Goleary/animated map
  _src/_assets/css/_dashboard.scss
  _src/_assets/js/dashboard-map.js
  _src/dashboard.md
Labels: Visualization 📈

#230 Add basic animated/scrubber map
  _src/_assets/css/_dashboard.css
  _src/_assets/css/_dashboard.scss
  _src/_assets/css/all.scss
  _src/_assets/js/dashboard-map.js
  _src/dashboard.md
Labels: Visualization 📈
