Repository COVID19Tracking/website, pull requests merged in 2020-06, with the labels that each got.

#1046 Refactor global sheet 1030
  src/__tests__/components/common/__snapshots__/container.js.snap
  src/__tests__/components/common/__snapshots__/contentful-content.js.snap
  src/__tests__/components/layout/__snapshots__/footer.js.snap
  src/__tests__/components/layout/__snapshots__/header.js.snap
  src/__tests__/components/layout/__snapshots__/index.js.snap
  src/__tests__/components/pages/blog/__snapshots__/blog-lede.js.snap
  src/__tests__/components/pages/blog/__snapshots__/blog-teaser-list.js.snap
  src/__tests__/components/pages/data/__snapshots__/state-data.js.snap
  src/__tests__/components/pages/data/__snapshots__/state-list.js.snap
  src/components/common/container.js
  src/components/common/container.module.scss
  src/components/common/contentful-content.js
  src/components/common/markdown-content.js
  src/components/common/markdown-content.module.scss
  src/components/pages/blog/blog-lede.js
  src/components/pages/blog/blog-teaser-list.js
  src/components/pages/blog/blog-teaser-list.module.scss
  src/components/pages/data/state-data.js
  src/components/pages/data/state-list.js
  src/components/pages/data/state-list.module.scss
  src/pages/404.js
  src/pages/about-data/visualization-guide/dashboard.module.scss
  src/pages/about-data/visualization-guide/index.js
  src/pages/contact/index.js
  src/pages/data/index.js
  src/pages/data/us-daily.js
  src/pages/search.js
  src/scss/global.scss
  src/templates/content.js
  src/templates/state.js
Labels: Project: Design System

#1051 feat(dev): Add danger to enforce style changes
  .github/workflows/danger.yml
  dangerfile.js
  package-lock.json
  package.json
  src/stories/1-docs/3-Styling.stories.mdx
Labels: Project: Design System

#1102 chore: Fix keyboard trap in search box
  package-lock.json
  package.json
  src/__tests__/components/layout/__snapshots__/footer.js.snap
  src/__tests__/components/layout/__snapshots__/header.js.snap
  src/__tests__/components/layout/__snapshots__/index.js.snap
  src/components/layout/footer.js
  src/components/layout/footer.module.scss
  src/components/layout/header/navigation.js
  src/components/layout/header/search/index.js
  src/components/layout/header/search/search-autocomplete.js
  src/components/layout/header/search/search-autocomplete.module.scss
  src/scss/global.scss
  src/scss/helpers.module.scss
Labels: accessibility

#1106 Refine blog author footer styles
  src/__tests__/components/pages/blog/__snapshots__/author-footer.js.snap
  src/components/pages/blog/author-footer.js
  src/components/pages/blog/author-footer.module.scss
Labels: DESIGN

#1117 chore: Add automerge action
  .github/workflows/automerge.yml
Labels: automerge

#1116 Add centered prop to layout, container
  src/__tests__/components/common/__snapshots__/container.js.snap
  src/__tests__/components/common/container.js
  src/components/common/container.js
  src/components/common/container.module.scss
  src/components/layout/index.js
Labels: automerge

#1107 chore(nav): center get involved button on small viewports
  src/components/layout/header/header.module.scss
Labels: DESIGN

#1127 fix(design): Add link back to blog on blog category pages
  src/templates/blog-category.js
Labels: automerge

#1140 chore(words): ARPC is becoming the Center for Antiracist Research
  src/__tests__/components/pages/homepage/__snapshots__/large-project.js.snap
  src/components/pages/homepage/large-project.js
  src/components/pages/race/header-hero.js
Labels: automerge
