Repository COVID19Tracking/website, pull requests merged in 2020-04, with the labels that each got.

#310 Revised header text
  src/components/common/hero.js
  src/images/card.png
Labels: CONTENT/EDITORIAL, DESIGN, V2: Implement in redesign

#347 Simplify Gatsby setup in README
  .env.example
  README.md
Labels: documentation

#350 Document required Node version
  .npmrc
  package.json
Labels: documentation

#334 Update stay-at-home orders on small multiples
  _src/_assets/css/_dashboard.scss
  _src/_assets/js/dashboard-charts.js
  _src/dashboard.md
Labels: Visualization 📈

#304 fix(dashboard): updated styles for button and fixed overlapping grid …
  _src/_assets/css/_dashboard.scss
  _src/_assets/js/d3-area-chart.js
  _src/_assets/js/dashboard-charts.js
  _src/dashboard.md
Labels: Visualization 📈

#295 feat(dashboard-map): multiple colors for chloropleth
  _src/_assets/css/_dashboard.scss
  _src/_assets/js/d3-legend.js
  _src/_assets/js/dashboard-map.js
  _src/dashboard.md
Labels: Visualization 📈

#332 Adjust dashboard layout to be single column
  _src/_assets/css/_dashboard.scss
  _src/_assets/js/d3-bar-chart.js
  _src/_assets/js/dashboard-charts.js
  _src/dashboard.md
Labels: Visualization 📈

#348 Update state grades (closes #242)
  src/components/common/state-data.js
  src/components/common/state-grade.js
  src/images/state-grades/grade-a.svg
  src/images/state-grades/grade-b.svg
  src/images/state-grades/grade-c.svg
  src/images/state-grades/grade-d.svg
  src/images/state-grades/grade-f.svg
  src/images/state-grades/grade-na.svg
  src/scss/components/common/state-data.scss
  src/scss/components/common/state-grade.scss
  src/templates/state.js
Labels: DESIGN

#409 Move React components to separate files
  src/components/pages/data/state-data.js
  src/components/pages/data/state-list.js
  src/components/pages/data/state-nav.js
  src/components/pages/state/screenshots.js
  src/components/pages/state/state-history.js
  src/components/pages/state/state-links.js
  src/pages/data/index.js
  src/scss/components/pages/data/state-data.scss
  src/templates/state.js
Labels: DEV

#411 Add .prettierignore for build and cached files
  .prettierignore
Labels: DEV

#423 Remove US total outcomes data
  src/components/common/summary-table.js
  src/pages/data/index.js
  src/pages/data/us-daily.js
Labels: CONTENT/EDITORIAL, DEV, Needs Data Approval

#402 feat(dashboard-gatsby):add bubble map with tooltips
  gatsby-config.js
  package-lock.json
  package.json
  src/pages/dashboard/_Map.js
  src/pages/dashboard/_MapContaner.js
  src/pages/dashboard/_utils.js
  src/pages/dashboard/charts/_ChoroLegend.js
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/charts/map.scss
  src/pages/dashboard/data/_state-populations.js
  src/pages/dashboard/index.js
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#396 Convert area chart to React
  package-lock.json
  package.json
  src/pages/dashboard/_AreaChart.js
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_SmallMultiplesAreaCharts.js
  src/pages/dashboard/_util.js
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/index.js
  src/scss/components/common/visualization.scss
Labels: Visualization 📈

#405 feat: Use snippet for 404 page
  src/pages/404.js
Labels: CONTENT/EDITORIAL

#432 converted US Area chart to use Gatsby data
  package-lock.json
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_SmallMultiplesAreaCharts.js
  src/pages/dashboard/_UsAreaChartContainer.js
  src/pages/dashboard/charts/_AreaChart.js
  src/pages/dashboard/index.js
Labels: Visualization 📈

#435 fix(visualization): Changed tooltip style for map
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/charts/map.scss
Labels: Visualization 📈

#436 Use GraphQL query for small multiples charts
  src/pages/dashboard/_SmallMultiplesContainer.js
  src/pages/dashboard/index.js
Labels: Visualization 📈

#446 feat(dashboard): converted map to use gatsby data
  src/data/visualization/state-populations.json
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/charts/_Map.js
Labels: Visualization 📈

#443 Break out dashboard into section containers that can fetch data
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_StateTotalDeathsContainer.js
  src/pages/dashboard/_UsAreaChartContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
  src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
  src/pages/dashboard/index.js
Labels: Visualization 📈

#447 Updated color set, closes #440
  src/scss/colors.scss
  src/scss/components/common/detail-text.scss
  src/scss/components/footer.scss
  src/scss/components/header.scss
  src/scss/components/hero.scss
  src/scss/components/pages/homepage/press-logos.scss
  src/scss/pages/data.scss
  src/scss/pages/homepage.scss
  src/stories/2-components/03-Colors.stories.js
Labels: DESIGN

#433 Add bar chart for total deaths in US on dashboard
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
  src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
  src/pages/dashboard/_util.js
  src/pages/dashboard/_utils.js
  src/pages/dashboard/charts/_AreaChart.js
  src/pages/dashboard/charts/_BarChart.js
Labels: Visualization 📈

#468 Add basic CDC chart with data from GraphQL API
  src/pages/dashboard/_CDCComparisonContainer.js
Labels: Visualization 📈

#461 Tweaking the color naming scheme (closes #460, closes #465)
  src/components/common/detail-text.module.scss
  src/components/layout/footer.module.scss
  src/components/layout/header.module.scss
  src/components/layout/hero.module.scss
  src/components/pages/data/state-data.module.scss
  src/components/pages/data/state-nav.module.scss
  src/components/pages/homepage/visualizations.module.scss
  src/pages/data/index.module.scss
  src/pages/index.module.scss
  src/scss/colors.scss
  src/stories/2-components/03-Colors.stories.js
Labels: DESIGN

#467 fix(charts): make links have state names #463
  src/pages/dashboard/_StateCumulativeTestsContainer.js
Labels: Visualization 📈

#449 fix(charts): reformat small area charts for legibility
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/charts/_AreaChart.js
  src/pages/dashboard/dashboard.scss
Labels: Visualization 📈

#473 feat(dashboard): add charts to storybook
  src/pages/dashboard/charts/_AreaChart.js
  src/pages/dashboard/charts/_BarChart.js
  src/pages/dashboard/charts/area-chart.scss
  src/pages/dashboard/dashboard.scss
  src/stories/2-components/15-Charts.stories.js
Labels: Visualization 📈

#448 feat: add date lable for map-time-scrubber, re: #441
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#482 Standardize language around testing in graphics
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
Labels: Visualization 📈

#451 fix(charts): remove focus from container, re: #429
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#491 Add tests per day to historical tables (closes #471)
  src/components/pages/state/state-history.js
  src/pages/data/us-daily.js
  src/templates/state.js
Labels: Needs Data Approval

#494 Add toggle to switch between states' total tests versus per capita
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_utils.js
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#495 add note, source and bylines at the bottom #488
  src/pages/dashboard/index.js
Labels: Visualization 📈

#500 fix(visualiztion): brings back focus and finetunes it,re #429
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#511 Move chart legend to right of toggle on large screens
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#476 feature(dashboard-gatsby-bar-chart): added total state deaths bar chart
  src/pages/dashboard/_StateCumulativeDeathsContainer.js
  src/pages/dashboard/_utils.js
  src/pages/dashboard/charts/_HorizontalBarChart.js
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/index.js
  src/pages/index.js
Labels: Visualization 📈

#504 fix(visualization): Style map slider
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#493 fix(chart):see all data from [state abbreviation] #478
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/dashboard.scss
Labels: Visualization 📈

#502 Fix tooltip tables styling
  src/pages/dashboard/_utils.js
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/charts/map.scss
Labels: Visualization 📈

#518 fix: update capitalization for choropleth dropdown
  src/pages/dashboard/_MapContainer.js
Labels: Visualization 📈

#514 fix(choropleth): update color schemes
  src/pages/dashboard/charts/_Map.js
Labels: Visualization 📈

#505 fix(visualization): Make sure outline of hovered state is on top
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#515 fix: Added stay at home date for MO, SC, TX
  src/pages/dashboard/_StateCumulativeTestsContainer.js
Labels: Visualization 📈

#524 fix: resized map
  src/pages/dashboard/charts/_Map.js
Labels: Visualization 📈

#523 fix(no-js-nav): in-page links to states
  src/components/pages/data/state-nav-no-script.js
Labels: bug

#522 fix: dashboard contributor spacing
  src/pages/dashboard/index.js
Labels: Visualization 📈

#526 fix(dashboard): improve map display on mobile and use global colors
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/charts/_ChoroLegend.js
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/charts/map.scss
  src/pages/dashboard/map-container.scss
  src/scss/breakpoints.scss
Labels: Visualization 📈

#540 Dashboard horiz bar fix
  src/pages/dashboard/_StateCumulativeDeathsContainer.js
  src/pages/dashboard/_StateTotalDeathsContainer.js
  src/pages/dashboard/charts/_HorizontalBarChart.js
  src/pages/dashboard/index.js
  src/pages/dashboard/state-cumulative-deaths-container.scss
Labels: Visualization 📈

#527 Update barchart size 503
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
  src/pages/dashboard/charts/_BarChart.js
Labels: Visualization 📈

#512 Make small multiple charts collapsible on smaller screens
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/dashboard.scss
Labels: Visualization 📈

#535 fix: text-heavy page design
  src/components/common/container.js
  src/components/common/container.module.scss
  src/components/layout/index.js
  src/pages/about-project/in-the-press.js
  src/pages/blog.js
  src/templates/blog-post.js
  src/templates/content.js
Labels: DESIGN

#552 Normalize CDC and Covid-19 Tracking data for comparison charts
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/charts/_BarChart.js
  src/pages/dashboard/charts/bar-chart.scss
  src/pages/dashboard/dashboard.scss
Labels: Visualization 📈

#559 Limit changes on :focus
  src/pages/dashboard/dashboard.scss
Labels: Visualization 📈

#568 fix(text-heavy): add L/R margins on smaller viewports
  src/components/common/container.module.scss
Labels: DESIGN

#428 Convert dashboard viz to use Gatsby
  gatsby-config.js
  package-lock.json
  package.json
  src/components/charts/area-chart.js
  src/components/charts/area-chart.scss
  src/components/charts/bar-chart.js
  src/components/charts/bar-chart.scss
  src/components/charts/horizontal-bar-chart.js
  src/data/visualization/state-populations.json
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_StateCumulativeDeathsContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
  src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
  src/pages/dashboard/charts/_ChoroLegend.js
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/charts/map.scss
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/index.js
  src/pages/dashboard/map-container.scss
  src/pages/dashboard/state-cumulative-deaths-container.scss
  src/pages/index.js
  src/scss/breakpoints.scss
  src/stories/2-components/15-Charts.stories.js
  src/utilities/visualization.js
Labels: Visualization 📈

#595 fix(dashboard):add light-gray bg to small multiple svgs #585, and sta…
  src/pages/dashboard/dashboard.scss
Labels: Visualization 📈

#601 Update headers style 569
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_StateCumulativeDeathsContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/index.js
Labels: Visualization 📈

#589 fix(dashboard): use consistent dashed outline styling for all focus states
  src/pages/dashboard/dashboard.scss
  src/scss/global.scss
Labels: Visualization 📈

#594 Update dashboard charts' grids and labels colors
  src/.DS_Store
  src/components/charts/area-chart.js
  src/components/charts/area-chart.scss
  src/components/charts/bar-chart.js
  src/components/charts/bar-chart.scss
  src/components/charts/charts.module.scss
  src/components/charts/horizontal-bar-chart.js
  src/pages/dashboard/_StateCumulativeDeathsContainer.js
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/map-container.scss
  src/utilities/visualization.js
Labels: Visualization 📈

#599 fix(charts): Add legend to "Positive tests and total tests in the US" chart
  src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
Labels: Visualization 📈

#612 fix(visualization):remove periods from months on the page #577
  src/utilities/visualization.js
Labels: Visualization 📈

#626 fix(dashboard): align map legend with toggle
  src/pages/dashboard/charts/map.scss
Labels: Visualization 📈

#616 fix(dashboard): ensure no hardcoded colors for data display
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
  src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
Labels: Visualization 📈

#607 fix(dashboard): update bubble legend style closes #593
  src/pages/dashboard/charts/_Map.js
  src/pages/dashboard/charts/map.scss
Labels: Visualization 📈

#584 fix(dashboard): Update HTML code characters
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/index.js
Labels: Visualization 📈

#619 fix(charts): adjust small multiples container for left and right alignment
  src/pages/dashboard/dashboard.scss
Labels: Visualization 📈

#618 fix(charts): 573/chart headers alignment
  src/components/charts/bar-chart.js
  src/components/charts/horizontal-bar-chart.js
  src/pages/dashboard/_CDCComparisonContainer.js
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_StateCumulativeDeathsContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_UsCumulativeDeathsContainer.js
  src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
  src/pages/dashboard/dashboard.module.scss
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/index.js
  src/pages/dashboard/map-container.scss
Labels: Visualization 📈

#625 fix(charts): use shared date extent for all small multiple charts
  src/components/charts/area-chart.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
Labels: Visualization

#633 fix(charts): 620 small multiple state names, no state keys version
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/dashboard.scss
  src/utilities/visualization.js
Labels: Visualization

#586 fix(dashboard): update US death chart color 563
  src/components/charts/bar-chart.js
  src/pages/dashboard/_UsDailyDeathsContainer.js
  src/pages/dashboard/index.js
Labels: Visualization

#624 fix(dashboard): adjust line-height of notes/byline section
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/index.js
Labels: Visualization

#642 feat(charts): added a tooltip to the area chart
  package-lock.json
  package.json
  src/components/charts/area-chart.js
  src/components/charts/bar-chart.js
  src/components/charts/tooltip.js
  src/components/charts/tooltip.module.scss
  src/pages/dashboard/_MapContainer.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/_TotalAndPositiveLegend.js
  src/pages/dashboard/_UsPositiveAndTotalTestsContainer.js
  src/pages/dashboard/map-container.scss
  src/pages/dashboard/total-and-positive-legend.module.scss
Labels: Visualization

#645 fix(charts): fix regression issues with charts layout and responsiveness
  src/components/charts/bar-chart.js
  src/components/charts/horizontal-bar-chart.js
Labels: Visualization

#663 fix(dashboard): improve experience for screen readers in cumulative tests by state section (small multiples)
  src/components/charts/area-chart.js
  src/components/charts/bar-chart.js
  src/pages/dashboard/_StateCumulativeTestsContainer.js
  src/pages/dashboard/dashboard.scss
Labels: Visualization

#668 fix(dashboard): fix y axis styling on bar & x axis on horizontal bar
  src/components/charts/area-chart.js
  src/components/charts/bar-chart.js
  src/components/charts/charts.module.scss
  src/components/charts/horizontal-bar-chart.js
Labels: Visualization

#669 fix(charts): add bottom margin back to US tests chart legend
  src/pages/about-data/visualization-guide/dashboard.scss
Labels: Visualization

#587 fix(dashboard): updated text content and formatting 576
  src/pages/about-data/visualization-guide/_CDCComparisonContainer.js
  src/pages/about-data/visualization-guide/index.js
Labels: Visualization

#683 fix(dashboard): make sure last element on sm multiples can be seen
  src/components/charts/area-chart.js
Labels: Visualization

#694 fix(dashboard): re add accidentally deleted name (mine!)
  src/pages/about-data/visualization-guide/index.js
Labels: Visualization

#692 Issue 688: Added margin to the press logos
  src/__tests__/components/pages/homepage/__snapshots__/press-logos.js.snap
  src/__tests__/components/pages/homepage/press-logos.js
  src/components/pages/homepage/press-logos.js
  src/components/pages/homepage/press-logos.module.scss
  src/pages/about-project/in-the-press.js
Labels: DESIGN
