Repository COVID19Tracking/website, pull requests merged in 2020-10, with the labels that each got.

#1491 fix(a11y): Label state nav with abbr
  src/components/pages/data/state-nav.js
Labels: accessibility

#1495 Language changes to volunteer form to make it friendlier
  src/components/pages/contact/volunteer-form.js
Labels: automerge

#1507 Add native lazy loading to blog img elements
  src/components/pages/blog/content-blocks/image-content-block.js
Labels: automerge

#1289 feat: add crdt shareable images
  .circleci/config.yml
  .eslintrc.js
  .nvmrc
  gatsby-config.js
  gatsby-node.js
  jest.config.js
  package.json
  plugins/gatsby-render-components/build-cache.js
  plugins/gatsby-render-components/gatsby-node.js
  plugins/gatsby-render-components/gatsby-ssr.js
  plugins/gatsby-render-components/index.js
  plugins/gatsby-render-components/package.json
  plugins/gatsby-render-components/prettify-url.js
  plugins/gatsby-render-components/rendered-component.js
  plugins/gatsby-source-covid-tracking-counties/index.js
  plugins/gatsby-transformer-covid-census/gatsby-node.js
  src/__tests__/components/pages/blog/__snapshots__/blog-lede.js.snap
  src/__tests__/components/pages/race/dashboard/__snapshots__/states.js.snap
  src/__tests__/components/social-media-graphics/race/__snapshots__/footnotes.js.snap
  src/__tests__/components/social-media-graphics/race/__snapshots__/header.js.snap
  src/__tests__/components/social-media-graphics/race/__snapshots__/no-data.js.snap
  src/__tests__/components/social-media-graphics/race/footnotes.js
  src/__tests__/components/social-media-graphics/race/header.js
  src/__tests__/components/social-media-graphics/race/no-data.js
  src/__tests__/components/social-media-graphics/race/utils.js
  src/components/common/detail-text.js
  src/components/common/detail-text.module.scss
  src/components/common/form.js
  src/components/common/landing-page/call-to-action.js
  src/components/common/social-sharing.js
  src/components/common/social-sharing.module.scss
  src/components/layout/header/return-links.module.scss
  src/components/pages/blog/blog-categories.module.scss
  src/components/pages/get-involved/form.module.scss
  src/components/pages/race/dashboard/states.js
  src/components/pages/race/dashboard/states.module.scss
  src/components/pages/race/infection-and-mortality-data/select.js
  src/components/pages/race/infection-and-mortality-data/share.js
  src/components/pages/race/infection-and-mortality-data/share.module.scss
  src/components/social-media-graphics/race/footnotes.js
  src/components/social-media-graphics/race/header.js
  src/components/social-media-graphics/race/locale.js
  src/components/social-media-graphics/race/no-data.js
  src/components/social-media-graphics/race/social-card.js
  src/components/social-media-graphics/race/social-card.module.scss
  src/components/social-media-graphics/race/social-cards.js
  src/components/social-media-graphics/race/utils.js
  src/components/utils/seo.js
  src/images/car-logo-small.png
  src/images/ctp-icon-small.png
  src/pages/race/infection-and-mortality-data.js
  src/templates/race/infection-and-mortality-data/landing.js
  src/templates/race/infection-and-mortality-data/landing.module.scss
  yarn.lock
Labels: not stale

#1523 fix(race): subnav items overlapping with builders image
  src/components/pages/race/header-hero.module.scss
Labels: automerge

#1529 dev: Added a custom develop command
  README.md
  package.json
Labels: automerge

#1541 Update volunteer-form.js
  src/components/pages/contact/volunteer-form.js
Labels: automerge

#1550 feat(blog): update language for related weekly update posts
  src/components/pages/blog/footer/related-posts.js
Labels: automerge
